blueprint:
  name: Paralelo Virtual GAMETAS
  description: Liga/Desliga todos os switchs/lights/fans do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os switchs/lights/fans
      selector:
            entity:
              domain:
                - switch
                - light
                - fan
              multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input entrada_switchs
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0

mode: single
